 Mechanical and Manufacturing Engineering                          13 SEP 2017
 University of New South Wales - 2016                                    21:23
 -----------------------------------------------------------------------------
<  1  0  0 AHU

aAHU   1    AHU1                

   Type ~ CV Zone Reheat without Reset                      No. Off ~  1
 
   Connected to ~ Chiller No   Boiler  No
   Floor Area ~   146 m2   Volume ~  657.0 m3   Average Ceiling Height ~ 4500. mm
>  1  0  0 AHU
<  0  0  0 ERRORS
 INPUT DATA COMMENT ~ THERE IS NO ROOF ENTERED IN THE PROJECT
>  0  0  0 ERRORS
<  1  0  0 ERRORS
 
>  1  0  0 ERRORS
<  1  0  0 COOLING

bAHU COOLING LOAD SUMMARY                       
c DESIGN COOLING LOAD IS    24.7 kW AT  3PM MAR
  DESIGN COOLING LOAD IS AT PEAK AHU GTH                                     
  AHU OPERATING HOURS  9AM TO  8PM. CALCS BASED ON 16 HOURS OPERATION FROM 6AM
d                                                     CDB      CWB     g/kg  %RH
  GTSH           18.2 kW          AVERAGE ROOM AIR   23.5     17.4     9.93 55.0
  GTLH           6.57 kW          AHU O/A            33.8     22.8    12.89     
  AHU SH FACT    0.73                                                           
  SUPPLY AIR     1306 l/s         COIL DEW POINT     10.8              8.06     
  AHU O/A           0 l/s         COIL LEAVING AIR   12.0 (N) 11.5     8.24     
  DEHUMID AIR    1306 l/s         COIL ENTERING AIR  23.5     17.4     9.93     
  AIR ch/hr       7.2             RETURN AIR         23.5     17.4     9.93     
  l/s/m2          8.9             AVERAGE ROOM ENT.  12.0     11.5     8.24     
  l/s/kW         52.8             BYPASS FACTOR      0.09                       
  W/m2            169             MIX R/A AND O/A    23.5     17.4     9.93     
                                                                                
 NOTE : (N) MEANS NOMINATED VALUE USED
>  1  0  0 COOLING
<  1  0  0 HEATING
 
bAHU HEATING LOAD CHART & SUMMARY
 
d SENSIBLE 

  FABRIC LOAD                                 =   10.9 kW
  WARM UP ( 21.4% = 25.00% x  0.95 x  0.90)   =   2.33 kW
  
d TOTAL AHU HEATING LOAD (EXCL. HUMIDIFIER)   =   13.2 kW
 
d LATENT 
 
  INFILTRATION    383. l/s x 9.28 g/kg x 2.97 =   10.6 KW
  AHU O/A           0. l/s x 9.28 g/kg x 2.97 =   0.00 KW
                                               -------
                              HUMIDIFIER LOAD =   10.6 KW (213 g/min water)
 
  SUPPLY AIR     1306 l/s         ROOM AIR           21.0 CDB 80.0%RH  18.6 CWB
  AHU O/A           0 l/s         OUTDOOR AIR         0.7 CDB 80.0%RH          
  W/m2             91             RETURN AIR         21.0 CDB                  
  W/m3           20.1             COIL LEAVING AIR   29.4 CDB                  
                                  COIL ENTERING AIR  21.0 CDB                  
>  1  0  0 HEATING
<  1  0  0 COOLING LOAD CHART
                                                                              
bAHU COOLING LOAD CHART AT NOMINATED TIME  3PM DEC                            
 AHU OPERATING HOURS  9AM TO  8PM. CALCS BASED ON 16 HOURS OPERATION FROM 6AM
 
dACCUMULATED ZONE/ROOM ADJUSTED HEAT                                          
     ADJUSTED ROOM SENSIBLE                                  =  16471         
     SUM OF ZONE REHEAT                                      =   1701         
     ADJUSTED ROOM LATENT                                    =   6741         
                                                              -------         
                                         ADJUSTED TOTAL HEAT =         24913  
d                                   COOLING GRAND TOTAL HEAT =         24913  
                           COOLING GRAND TOTAL SENSIBLE HEAT =         18172  
                             COOLING GRAND TOTAL LATENT HEAT =          6741  
 
dZONE REHEAT
  NO.  kW 
  ------- 
   1 1.70 
  ------- 
>  1  0  0 COOLING LOAD CHART
<  2  0  0 AHU

aAHU   2    AHU2                

   Type ~ CV Zone Reheat without Reset                      No. Off ~  1
 
   Connected to ~ Chiller No   Boiler  No
   Floor Area ~   440 m2   Volume ~ 1980.0 m3   Average Ceiling Height ~ 4500. mm
>  2  0  0 AHU
<  2  0  0 ERRORS
 
>  2  0  0 ERRORS
<  2  0  0 COOLING

bAHU COOLING LOAD SUMMARY                       
c DESIGN COOLING LOAD IS    75.7 kW AT  4PM MAR
  DESIGN COOLING LOAD IS AT PEAK AHU GTH                                     
  AHU OPERATING HOURS  9AM TO  8PM. CALCS BASED ON 16 HOURS OPERATION FROM 6AM
d                                                     CDB      CWB     g/kg  %RH
  GTSH           58.2 kW          AVERAGE ROOM AIR   23.5     17.4     9.93 55.0
  GTLH           17.6 kW          AHU O/A            32.8     22.5    12.89     
  AHU SH FACT    0.77                                                           
  SUPPLY AIR     4180 l/s         COIL DEW POINT     11.5              8.47     
  AHU O/A           0 l/s         COIL LEAVING AIR   12.0 (N) 11.8     8.52     
  DEHUMID AIR    4180 l/s         COIL ENTERING AIR  23.5     17.4     9.93     
  AIR ch/hr       7.6             RETURN AIR         23.5     17.4     9.93     
  l/s/m2          9.5             AVERAGE ROOM ENT.  12.0     11.8     8.52     
  l/s/kW         55.2             BYPASS FACTOR      0.04                       
  W/m2            172             MIX R/A AND O/A    23.5     17.4     9.93     
                                                                                
 NOTE : (N) MEANS NOMINATED VALUE USED
>  2  0  0 COOLING
<  2  0  0 HEATING
 
bAHU HEATING LOAD CHART & SUMMARY
 
d SENSIBLE 

  FABRIC LOAD                                 =   31.8 kW
  WARM UP ( 27.5% = 25.00% x  1.22 x  0.90)   =   8.75 kW
  
d TOTAL AHU HEATING LOAD (EXCL. HUMIDIFIER)   =   40.6 kW
 
d LATENT 
 
  INFILTRATION    880. l/s x 9.28 g/kg x 2.97 =   24.2 KW
  AHU O/A           0. l/s x 9.28 g/kg x 2.97 =   0.00 KW
                                               -------
                              HUMIDIFIER LOAD =   24.2 KW (490 g/min water)
 
  SUPPLY AIR     4180 l/s         ROOM AIR           21.0 CDB 80.0%RH  18.6 CWB
  AHU O/A           0 l/s         OUTDOOR AIR         0.7 CDB 80.0%RH          
  W/m2             92             RETURN AIR         21.0 CDB                  
  W/m3           20.5             COIL LEAVING AIR   29.0 CDB                  
                                  COIL ENTERING AIR  21.0 CDB                  
>  2  0  0 HEATING
<  2  0  0 COOLING LOAD CHART
                                                                              
bAHU COOLING LOAD CHART AT NOMINATED TIME  3PM DEC                            
 AHU OPERATING HOURS  9AM TO  8PM. CALCS BASED ON 16 HOURS OPERATION FROM 6AM
 
dACCUMULATED ZONE/ROOM ADJUSTED HEAT                                          
     ADJUSTED ROOM SENSIBLE                                  =  53805         
     SUM OF ZONE REHEAT                                      =   4365         
     ADJUSTED ROOM LATENT                                    =  17950         
                                                              -------         
                                         ADJUSTED TOTAL HEAT =         76120  
d                                   COOLING GRAND TOTAL HEAT =         76120  
                           COOLING GRAND TOTAL SENSIBLE HEAT =         58170  
                             COOLING GRAND TOTAL LATENT HEAT =         17950  
 
dZONE REHEAT
  NO.  kW 
  ------- 
   1 4.36 
  ------- 
>  2  0  0 COOLING LOAD CHART
